### ISSUE TITLE
Deadlock on WS Connection Close

### ISSUE THREAD

**Issue by Kr0llx** [enbility/ship-go#11]
# Problem Description
The following use-case should be assumed. Two ship nodes EVSE and HEMS. The EVSE makes a connection attempt to the HEMS which, however, refuses. The shortened log of the EVSE looks like this:

```
13:06:03 INFO  Local SKI:  41c98b1bbe5fc7657ce311981951f12d304ab419
...
13:06:04 DEBUG ski: 23ef43d7a6487fb9a44c7fbb0d2b840514b8faa6 name: Demo-HEMS-123456789 brand: Demo model: HEMS typ: EnergyManagementSystem identifier: Demo-HEMS-123456789 register: false host: partex.local port: 4815 addresses: [127.0.0.1]
13:06:04 DEBUG delaying connection to 23ef43d7a6487fb9a44c7fbb0d2b840514b8faa6 by 138ms to minimize double connection probability
13:06:04 DEBUG trying to connect to 23ef43d7a6487fb9a44c7fbb0d2b840514b8faa6 at xxx.local
13:06:04 DEBUG initiating connection to 23ef43d7a6487fb9a44c7fbb0d2b840514b8faa6 at xxx.local:4815/ship/
...
13:06:04 TRACE Recv: 23ef43d7a6487fb9a44c7fbb0d2b840514b8faa6 {"connectionHello":[{"phase":"pending"},{"waiting":60000}]}
13:06:04 TRACE Send: 23ef43d7a6487fb9a44c7fbb0d2b840514b8faa6 {"connectionHello":[{"phase":"ready"},{"waiting":60000}]}
13:06:04 TRACE Recv: 23ef43d7a6487fb9a44c7fbb0d2b840514b8faa6 {"connectionHello":[{"phase":"aborted"}]}
13:06:04 TRACE 23ef43d7a6487fb9a44c7fbb0d2b840514b8faa6 SHIP state changed to: 16
13:06:05 DEBUG 23ef43d7a6487fb9a44c7fbb0d2b840514b8faa6 websocket read error:  websocket: close 4452: Node rejected by application
10:06:05 DEBUG 23ef43d7a6487fb9a44c7fbb0d2b840514b8faa6 error writing to websocket:  websocket: close sent
```

It can be seen that the connection request has been denied as expected. Later the HEMS initiates a connection to the EVSE. The log shows the following:

```
10:17:54 DEBUG incoming connection request from 23ef43d7a6487fb9a44c7fbb0d2b840514b8faa6
10:17:54 DEBUG closing incoming double connection, as the existing connection will be used
```

An incoming connection can be seen. The connection is then closed because there is supposedly already another connection. However this is should not be the case, as this is the connection that has been closed in the first connection attempt.

This results in the HEMS not being able to connect to the EVSE. As the EVSE thinks there is already a connection.

# Possible Reason
The reason could be a deadlock in the function `CloseConnection(...)`.
https://github.com/enbility/ship-go/blob/14685b670c3d84c05d6d1f940b214a0ca7dcc810/ship/connection.go#L151

## How?!
1. The connection request of the EVSE to the HEMS is `aborted` by the HEMS.
2. This results in the function `CloseConnection(...)` being invoked.
3. In this function the function `CloseDataConnection(...)` is called:
https://github.com/enbility/ship-go/blob/14685b670c3d84c05d6d1f940b214a0ca7dcc810/ship/connection.go#L184
4.This function checks whether the connection is already closed and sends a reason if not.
https://github.com/enbility/ship-go/blob/14685b670c3d84c05d6d1f940b214a0ca7dcc810/ws/websocket.go#L287-L293
5. This function then checks again if the connection still exists and sends the message otherwise.
https://github.com/enbility/ship-go/blob/14685b670c3d84c05d6d1f940b214a0ca7dcc810/ws/websocket.go#L268-L280
6. However, if now the send fails. E.g. if the connection has been closed in between checking and sending. A error is returned and therefore the function `closeWithError(...)` is called.
https://github.com/enbility/ship-go/blob/14685b670c3d84c05d6d1f940b214a0ca7dcc810/ws/websocket.go#L143C1-L147C2
7. This function calls `ReportConnectionError(err)`
https://github.com/enbility/ship-go/blob/14685b670c3d84c05d6d1f940b214a0ca7dcc810/ship/connection.go#L294
8. Which again calls `CloseConnection(...)` from step 2
9. Here lies the problem as the function `CloseConnection(...)` uses a `sync.Once.do(...)` call which is blocks until the first call ends, whis is not possible as it is called recursively. Resulting in a **Deadlock**.
https://github.com/enbility/ship-go/blob/14685b670c3d84c05d6d1f940b214a0ca7dcc810/ship/connection.go#L151-L153

# Solution
No apparent solution.
- Checking if `CloseConnection(...)` has been run allready would be possible but this defeats the usage of `sync.Once.do(...)` in the first place.
- Maybe find a better separation of the `CloseConnection(...)` content in order to prevent this from happening.
- Don't send in connection close.

**Comment by DerAndereAndi** [comment]
Thanks for the great bug report and the fix already. Awesome!
