### ISSUE TITLE
Deadlock on DisconnectSKI

### ISSUE THREAD

**Issue by Kr0llx** [enbility/ship-go#13]
# Description
The following use-case should be assumed. Two ship nodes EVSE and HEMS. The HEMS successfully connects to the EVSE. Now the HEMS wants to disconnect and uses the `Service.DisconnectSKI(...)` method. 

## Observation
The EVSE gets the disconnect and successfully removes the connection. The HEMS however never shows the successful disconnect, and is then also not able to connect to the same EVSE again.

## Problem
After invoking the `Service.DisconnectSKI(...)` method the call tree will eventually end at the following point:
https://github.com/enbility/ship-go/blob/14685b670c3d84c05d6d1f940b214a0ca7dcc810/hub/hub_pairing.go#L100-L111

As can be seen the corresponding connection for the given **ski** is accessed. For this the mutex **muxCon** is used. Note tho, that the `muxCon.close()` is **deferred**. This means that it is only unlocked when the above function returns.

However inside the following `con.CloseConnection(...)` method **muxCon** is used again, resulting in a deadlock. The the corresponding positions  are listed below.

https://github.com/enbility/ship-go/blob/14685b670c3d84c05d6d1f940b214a0ca7dcc810/hub/hub_shipconnection.go#L23-L26

https://github.com/enbility/ship-go/blob/14685b670c3d84c05d6d1f940b214a0ca7dcc810/hub/hub_connections.go#L453-L463

**Comment by DerAndereAndi** [comment]
Another great find and report! Thank you so much.
