### ISSUE TITLE
Problems with SHIP 13.4.6 Access Methods Identification

### ISSUE THREAD

**Issue by borg42** [enbility/ship-go#37]
I am currently implementing an embedded SHIP implementation for low end MCUs and testing it against ship-go.
All works fine until the SME "Access methods request" message comes in.

Here you can see what i send and the error that is thrown:
```
2024-09-29 21:24:52 TRACE Recv: 41c98b1bbe5fc7657ce311981951f12d304ab419 {"accessMethods":[{"id":"Tinkerforge-WARP3-12345"},{"dnsSd_mDns":[]},{"dns":[{"uri":"wss://192.168.0.33/ship/:4712"}]}]}
2024-09-29 21:24:52 TRACE 41c98b1bbe5fc7657ce311981951f12d304ab419 SHIP state changed to: 39
2024-09-29 21:24:52 DEBUG 41c98b1bbe5fc7657ce311981951f12d304ab419 SHIP handshake error: json: cannot unmarshal object into Go struct field AccessMethodsType.accessMethods.dns of type string
```

I think the form
`{"dns":[{"uri":"wss://192.168.0.33:4712/ship/"}]}`
conforms to the standard, but ship-go doesn't accept it.

On a side note: I am not sure if the uri with wss:// and path and port is what is actually expected here. Hard to find any examples of this stuff...

**Comment by DerAndereAndi** [comment]
Hi, you seem to be the first one to actually implement this field ;)

You can see the reason for this implementation in the code at https://github.com/enbility/ship-go/blob/dev/model/model.go#L184-L189

```
type AccessMethodsType struct {
	Id        *string    `json:"id"`
	DnsSdMDns *DnsSdMDns `json:"dnsSd_mDns,omitempty"`
	// According to the Spec Dns should be of type *Dns, but the SHM 2.0 only uses a string and would cause a crash
	Dns *string `json:"dns,omitempty"`
}
```

Also the SHIP documentation says about the `Dns` field:

> SHALL be present if the originator provides its SHIP service with unicast DNS.

Are you really supporting unicast DNS?

**Comment by DerAndereAndi** [comment]
I just re-tested this with the latest SMA HM 2.0 Firmware version, at it seems to be fixed there. So I updated the model to the correct data structure. The code in the dev branch should now work properly for you.

But I still think, you shouldn't use the `dns` field anyways ;)

**Comment by borg42** [comment]
> But I still think, you shouldn't use the `dns` field anyways ;)

Well, i interpret it as an optional parameter that i can implement if i want to, but need to implement if i use unicast DNS.

I did end up implementing it since it says in the next line that "accessMethods.dns.uri" is mandatory (which kind of conflicts with accessMethods.dns being optional).

They really should have provided a reference implementation. If we end up with N implementations from N different people they will all interpret stuff like this differently and everyone will end up with hacks like you had beforehand to be compatible with others...

Anyway, this issue can be closed since it is fixed now from my perspective :).

**Comment by DerAndereAndi** [comment]
The specification should be interpreted differently:

- If you add the `dns` information, then `uri` below it is mandatory. You may not only use `dns` without `uri`
- It is optional, but if you do NOT support unicast DNS, then you also should not use it. So if you add the information, and unicast DNS does not work, you would be providing wrong information.

Regarding your last comment: yep, that's what working with EEBUS is. Once you get into SPINE, there will be and is lots more to be interpreted differently.
