### ISSUE TITLE
Websocket may never actively connect to someone else

### ISSUE THREAD

**Issue by myz123126** [enbility/ship-go#43]
In  mdns/mdns.go
func (m *MdnsManager) Start(cb api.MdnsReportInterface) error {
	m.report = cb   is too late,

and when client has find server, m.report is nil

**Comment by myz123126** [comment]
should fix like this
![微信截图_20241118103459](https://github.com/user-attachments/assets/587b0d26-4875-425a-a6bb-614249197b60)

**Comment by DerAndereAndi** [comment]
Thank you, that is a good point.
