### ISSUE TITLE
Lack of Notification for Removed Ship Nodes via Avahi mDNS Integration

### ISSUE THREAD

**Issue by Kr0llx** [enbility/ship-go#8]
# Description
When a ship node is added, the Avahi mDNS picks it up and notifies the application through the `api.ServiceReaderInterface` about all currently visible services. However, when a ship node is removed, no update is sent. This poses a challenge for the implementer of the interface as there's no indication that the node is no longer available.

# Version
Tested with CEMd ([577b756](https://github.com/enbility/cemd/commit/577b756484cffb5f00981e2b2040bf431d7347f7)) and eebus-go ([45c4e2d](https://github.com/enbility/eebus-go/commit/45c4e2d20a818005278ef7a98f3a107cae3f9a12))

# Expected Behavior
The implementer of the `api.ServiceReaderInterface` gets also updated when a ship node gets removed.

**Comment by DerAndereAndi** [comment]
Thanks for the bug report and the PR for that. It is great to see the first contribution for this repo :)
